<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Sockseek.Infrastructure</AssemblyName>
    <RootNamespace>Sockseek.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sockseek.Application\Sockseek.Application.csproj" />
    <ProjectReference Include="..\Sockseek.Domain\Sockseek.Domain.csproj" />
  </ItemGroup>
</Project>
