// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sockseek.Infrastructure.Persistence;

#nullable disable

namespace Sockseek.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SockseekDbContext))]
    partial class SockseekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.AppProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppProfiles", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.CanonicalTrackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isrc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicBrainzRecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedArtist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CanonicalTracks", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.DownloadWorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EngineJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlaylistItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistItemId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("DownloadWorkflows", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ExternalAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("ExternalAccounts", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ExternalPlaylistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Provider", "ExternalId", "AccountId")
                        .IsUnique();

                    b.ToTable("ExternalPlaylists", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.LocalMediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CanonicalTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTrackId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("LocalMediaFiles", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.PlaylistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalPlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPlaylistId");

                    b.ToTable("Playlists", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.PlaylistItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanonicalTrackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTrackId");

                    b.HasIndex("PlaylistId", "ProviderItemId")
                        .IsUnique();

                    b.ToTable("PlaylistItems", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ProviderSyncStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "AccountId", "ResourceId")
                        .IsUnique();

                    b.ToTable("ProviderSyncStates", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ResolutionAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CandidateTrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EngineJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlaylistItemId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CandidateTrackId");

                    b.HasIndex("PlaylistItemId");

                    b.ToTable("ResolutionAttempts", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.SchemaInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastBackupUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchemaInfo", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.TrackSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawMetadataJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTrackId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("TrackSources", (string)null);
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.DownloadWorkflowEntity", b =>
                {
                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.PlaylistItemEntity", "PlaylistItem")
                        .WithMany("DownloadWorkflows")
                        .HasForeignKey("PlaylistItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlaylistItem");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ExternalPlaylistEntity", b =>
                {
                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.ExternalAccountEntity", "Account")
                        .WithMany("Playlists")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.LocalMediaFileEntity", b =>
                {
                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.CanonicalTrackEntity", "CanonicalTrack")
                        .WithMany("LocalMediaFiles")
                        .HasForeignKey("CanonicalTrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalTrack");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.PlaylistEntity", b =>
                {
                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.ExternalPlaylistEntity", "ExternalPlaylist")
                        .WithMany("Playlists")
                        .HasForeignKey("ExternalPlaylistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExternalPlaylist");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.PlaylistItemEntity", b =>
                {
                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.CanonicalTrackEntity", "CanonicalTrack")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("CanonicalTrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.PlaylistEntity", "Playlist")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalTrack");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ResolutionAttemptEntity", b =>
                {
                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.CanonicalTrackEntity", "CandidateTrack")
                        .WithMany("ResolutionAttempts")
                        .HasForeignKey("CandidateTrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.PlaylistItemEntity", "PlaylistItem")
                        .WithMany("ResolutionAttempts")
                        .HasForeignKey("PlaylistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateTrack");

                    b.Navigation("PlaylistItem");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.TrackSourceEntity", b =>
                {
                    b.HasOne("Sockseek.Infrastructure.Persistence.Entities.CanonicalTrackEntity", "CanonicalTrack")
                        .WithMany("Sources")
                        .HasForeignKey("CanonicalTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalTrack");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.CanonicalTrackEntity", b =>
                {
                    b.Navigation("LocalMediaFiles");

                    b.Navigation("PlaylistItems");

                    b.Navigation("ResolutionAttempts");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ExternalAccountEntity", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.ExternalPlaylistEntity", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.PlaylistEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sockseek.Infrastructure.Persistence.Entities.PlaylistItemEntity", b =>
                {
                    b.Navigation("DownloadWorkflows");

                    b.Navigation("ResolutionAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
