namespace Sockseek.Desktop;

public static class DesktopStringResources
{
    private static readonly IReadOnlyDictionary<string, string> Strings = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Shell.Window.Title"] = "Sockseek",
        ["Shell.Home.Title"] = "Home",
        ["Shell.Home.Description"] = "Backend status, recent activity, and onboarding live here.",
        ["Shell.Home.EmptyState.Title"] = "Daemon, library, and account readiness will anchor this home view.",
        ["Shell.Home.EmptyState.Description"] = "Use this page to confirm the local backend is healthy, see recent workflows, and pick up any unfinished setup before deeper navigation.",
        ["Shell.Home.Highlight1.Title"] = "Daemon health and handshake",
        ["Shell.Home.Highlight1.Description"] = "Connection state, restart recovery, and localhost session details stay visible here.",
        ["Shell.Home.Highlight2.Title"] = "Recent activity rollup",
        ["Shell.Home.Highlight2.Description"] = "Completed downloads, library scans, and playlist imports will surface in a single summary feed.",
        ["Shell.Home.Highlight3.Title"] = "Onboarding follow-ups",
        ["Shell.Home.Highlight3.Description"] = "Library folders, Soulseek sign-in, and provider setup nudges will live in this first-stop overview.",
        ["Shell.Home.Summary.Title"] = "Live shell summary",
        ["Shell.Home.Summary.Description"] = "This card already reflects the desktop shell's real daemon/session state while the rest of Home stays placeholder-only.",
        ["Shell.Home.Summary.BackendState.Label"] = "Backend state",
        ["Shell.Home.Summary.EventsState.Label"] = "Live events",
        ["Shell.Home.Summary.Handshake.Label"] = "Secure session",
        ["Shell.Home.Summary.BackendUrl.Label"] = "Backend URL",
        ["Shell.Home.Summary.StartCapability.Label"] = "Daemon launch",
        ["Shell.Home.Summary.State.Starting"] = "Starting",
        ["Shell.Home.Summary.State.Connected"] = "Connected",
        ["Shell.Home.Summary.State.Restarting"] = "Restarting",
        ["Shell.Home.Summary.State.Disconnected"] = "Disconnected",
        ["Shell.Home.Summary.State.Unauthorized"] = "Session expired",
        ["Shell.Home.Summary.State.Unknown"] = "Unknown",
        ["Shell.Home.Summary.Handshake.Available"] = "Available",
        ["Shell.Home.Summary.Handshake.Waiting"] = "Waiting for handshake",
        ["Shell.Home.Summary.BackendUrl.Unavailable"] = "Unavailable",
        ["Shell.Home.Summary.StartCapability.Ready"] = "Ready to launch from this shell",
        ["Shell.Home.Summary.StartCapability.Unavailable"] = "No launch path configured",
        ["Shell.Home.Summary.Events.Disconnected"] = "Disconnected",
        ["Shell.Home.Summary.Events.Connecting"] = "Connecting",
        ["Shell.Home.Summary.Events.Connected"] = "Connected",
        ["Shell.Home.Summary.Events.Reconnecting"] = "Reconnecting",
        ["Shell.Search.Title"] = "Search",
        ["Shell.Search.Description"] = "Track and album search UI will appear here.",
        ["Shell.Search.EmptyState.Title"] = "No search session is active yet.",
        ["Shell.Search.EmptyState.Description"] = "This space is reserved for track, album, and fallback lookup flows with fast keyboard-first query entry and live result updates.",
        ["Shell.Search.Highlight1.Title"] = "Search composer",
        ["Shell.Search.Highlight1.Description"] = "Global query input, filter chips, and quality hints will sit above the result stream.",
        ["Shell.Search.Highlight2.Title"] = "Result ranking and actions",
        ["Shell.Search.Highlight2.Description"] = "Candidates will expose bitrate, source, speed, and quick actions for resolve or download.",
        ["Shell.Search.Highlight3.Title"] = "Workflow continuity",
        ["Shell.Search.Highlight3.Description"] = "Reconnect-safe search state will keep long-running lookups visible even after backend restarts.",
        ["Shell.Playlists.Title"] = "Playlists",
        ["Shell.Playlists.Description"] = "Imported playlists and resolution progress will appear here.",
        ["Shell.Playlists.EmptyState.Title"] = "Imported playlists have not been staged yet.",
        ["Shell.Playlists.EmptyState.Description"] = "When provider and manual imports land, this area will show sync progress, unresolved tracks, and bulk actions without leaving the desktop shell.",
        ["Shell.Playlists.Highlight1.Title"] = "Import and sync overview",
        ["Shell.Playlists.Highlight1.Description"] = "Playlist cards will summarize provider, item counts, last sync, and drift from the source snapshot.",
        ["Shell.Playlists.Highlight2.Title"] = "Resolution queue",
        ["Shell.Playlists.Highlight2.Description"] = "Unmatched items and review-needed tracks will stay grouped so the user can clear blockers quickly.",
        ["Shell.Playlists.Highlight3.Title"] = "Bulk download workflow",
        ["Shell.Playlists.Highlight3.Description"] = "Download-missing, retry, and resolve actions will be coordinated from this section.",
        ["Shell.Library.Title"] = "Library",
        ["Shell.Library.Description"] = "Local library browsing and scans will appear here.",
        ["Shell.Library.EmptyState.Title"] = "Library roots still need indexing.",
        ["Shell.Library.EmptyState.Description"] = "This section will become the authoritative local catalog for tracks, albums, and scan health once filesystem wiring is complete.",
        ["Shell.Library.Highlight1.Title"] = "Roots and scan status",
        ["Shell.Library.Highlight1.Description"] = "Configured folders, scan progress, and write-permission issues will remain visible at a glance.",
        ["Shell.Library.Highlight2.Title"] = "Track and album browsing",
        ["Shell.Library.Highlight2.Description"] = "Local metadata, artwork presence, and file-backed playback readiness will surface here.",
        ["Shell.Library.Highlight3.Title"] = "Repair actions",
        ["Shell.Library.Highlight3.Description"] = "Relink, rescan, and duplicate-safe cleanup tools will live alongside the catalog.",
        ["Shell.Downloads.Title"] = "Downloads",
        ["Shell.Downloads.Description"] = "Active and completed download workflows will appear here.",
        ["Shell.Downloads.EmptyState.Title"] = "No download workflows are running right now.",
        ["Shell.Downloads.EmptyState.Description"] = "Queued, active, failed, and completed transfers will eventually share one recovery-friendly timeline in this section.",
        ["Shell.Downloads.Highlight1.Title"] = "Queue and transfer health",
        ["Shell.Downloads.Highlight1.Description"] = "Live progress, speeds, peers, and stalled-state warnings will be grouped in one operational view.",
        ["Shell.Downloads.Highlight2.Title"] = "Candidate fallback",
        ["Shell.Downloads.Highlight2.Description"] = "Retry and next-candidate actions will remain close to each workflow instead of being buried in logs.",
        ["Shell.Downloads.Highlight3.Title"] = "Completed file handoff",
        ["Shell.Downloads.Highlight3.Description"] = "Finished downloads will bridge cleanly into library indexing and local playback status.",
        ["Shell.Accounts.Title"] = "Accounts",
        ["Shell.Accounts.Description"] = "Provider connections and authorization status will appear here.",
        ["Shell.Accounts.EmptyState.Title"] = "No provider or Soulseek account is connected yet.",
        ["Shell.Accounts.EmptyState.Description"] = "This section is where local credentials, provider status, and quota warnings will be managed without exposing secrets in the UI.",
        ["Shell.Accounts.Highlight1.Title"] = "Connection cards",
        ["Shell.Accounts.Highlight1.Description"] = "Each provider will show auth state, capabilities, and the last successful handshake or sync.",
        ["Shell.Accounts.Highlight2.Title"] = "Secret-safe status",
        ["Shell.Accounts.Highlight2.Description"] = "Tokens and passwords stay local while the shell only surfaces opaque state and recovery actions.",
        ["Shell.Accounts.Highlight3.Title"] = "User guidance",
        ["Shell.Accounts.Highlight3.Description"] = "Quota, approval, and reconnect prompts will use plain language instead of raw auth errors.",
        ["Shell.Settings.Title"] = "Settings",
        ["Shell.Settings.Description"] = "Theme, daemon, and library preferences will appear here.",
        ["Shell.Settings.EmptyState.Title"] = "Desktop preferences are not configurable here yet.",
        ["Shell.Settings.EmptyState.Description"] = "Appearance, daemon launch defaults, storage roots, and diagnostics controls will graduate into this section as the shell fills out.",
        ["Shell.Settings.Highlight1.Title"] = "Appearance and shortcuts",
        ["Shell.Settings.Highlight1.Description"] = "Theme selection, localization-ready labels, and keyboard behavior will remain centralized here.",
        ["Shell.Settings.Highlight2.Title"] = "Daemon and diagnostics",
        ["Shell.Settings.Highlight2.Description"] = "Launch mode, recovery toggles, and safe diagnostic export belong in this control area.",
        ["Shell.Settings.Highlight3.Title"] = "Library and legal defaults",
        ["Shell.Settings.Highlight3.Description"] = "Storage roots, quality preferences, and user-facing compliance reminders will live here.",
        ["Shell.Navigation.Home.Hint"] = "Home (Ctrl+1)",
        ["Shell.Navigation.Search.Hint"] = "Search (Ctrl+L)",
        ["Shell.Navigation.Playlists.Hint"] = "Playlists (Ctrl+2)",
        ["Shell.Navigation.Library.Hint"] = "Library (Ctrl+3)",
        ["Shell.Navigation.Downloads.Hint"] = "Downloads (Ctrl+4)",
        ["Shell.Navigation.Accounts.Hint"] = "Accounts (Ctrl+5)",
        ["Shell.Navigation.Settings.Hint"] = "Settings (Ctrl+,)",
        ["Shell.CommandPalette.Title"] = "Command palette",
        ["Shell.CommandPalette.Placeholder"] = "Jump to a section or action",
        ["Shell.CommandPalette.NavigateHome"] = "Go to Home",
        ["Shell.CommandPalette.NavigateSearch"] = "Go to Search",
        ["Shell.CommandPalette.NavigatePlaylists"] = "Go to Playlists",
        ["Shell.CommandPalette.NavigateLibrary"] = "Go to Library",
        ["Shell.CommandPalette.NavigateDownloads"] = "Go to Downloads",
        ["Shell.CommandPalette.NavigateAccounts"] = "Go to Accounts",
        ["Shell.CommandPalette.NavigateSettings"] = "Go to Settings",
        ["Shell.Page.Highlights.Title"] = "What This Section Will Do",
        ["Shell.Home.LiveDataBadge"] = "LIVE",
        ["Shell.PlayerBar.Title"] = "Nothing playing",
        ["Shell.PlayerBar.Artwork"] = "Artwork placeholder",
        ["Shell.PlayerBar.Artwork.IconLabel"] = "Album artwork",
        ["Shell.PlayerBar.Artist"] = "Choose a local track or completed download",
        ["Shell.PlayerBar.Progress"] = "00:00 / --:--",
        ["Shell.PlayerBar.Progress.Hint"] = "Playback progress placeholder",
        ["Shell.PlayerBar.QueueSummary"] = "Queue unavailable until playback coordinator is connected",
        ["Shell.PlayerBar.Previous.IconLabel"] = "Previous track",
        ["Shell.PlayerBar.PlayPause.IconLabel"] = "Play or pause",
        ["Shell.PlayerBar.PlayPause.Hint"] = "Play or pause (Space)",
        ["Shell.PlayerBar.Next.IconLabel"] = "Next track",
        ["Shell.PlayerBar.Queue.IconLabel"] = "Queue",
        ["Shell.PlayerBar.Queue.Hint"] = "Queue placeholder",
        ["Shell.PlayerBar.Volume.IconLabel"] = "Volume",
        ["Shell.PlayerBar.Volume.Hint"] = "Volume placeholder",
        ["Shell.PlayerBar.ExpandedPlayer.IconLabel"] = "Expanded player",
        ["Shell.PlayerBar.ExpandedPlayer.Hint"] = "Expanded player placeholder",
        ["Shell.Backend.Starting.Title"] = "Starting local daemon",
        ["Shell.Backend.Starting.Message"] = "Sockseek is launching the backend and waiting for a secure session.",
        ["Shell.Backend.Starting.IconLabel"] = "Backend starting status",
        ["Shell.Backend.Connected.Title"] = "Connected",
        ["Shell.Backend.Connected.Message"] = "Local daemon is ready.",
        ["Shell.Backend.Connected.IconLabel"] = "Backend connected status",
        ["Shell.Backend.Restarting.Title"] = "Restarting local daemon",
        ["Shell.Backend.Restarting.Message"] = "The backend is restarting. UI actions will resume automatically.",
        ["Shell.Backend.Restarting.IconLabel"] = "Backend restarting status",
        ["Shell.Backend.Disconnected.Title"] = "Backend disconnected",
        ["Shell.Backend.Disconnected.Message"] = "Sockseek cannot currently reach the local daemon.",
        ["Shell.Backend.Disconnected.IconLabel"] = "Backend disconnected status",
        ["Shell.Backend.Unauthorized.Title"] = "Session expired",
        ["Shell.Backend.Unauthorized.Message"] = "The desktop shell needs a fresh local session handshake.",
        ["Shell.Backend.Unauthorized.IconLabel"] = "Backend session expired status",
        ["Shell.Backend.Unknown.Title"] = "Backend status unknown",
        ["Shell.Backend.Unknown.Message"] = "Sockseek cannot determine backend state yet.",
        ["Shell.Backend.Unknown.IconLabel"] = "Backend unknown status",
        ["Shell.Backend.Action.CopyDiagnostics.Label"] = "Copy diagnostics",
        ["Shell.Backend.Action.CopyDiagnostics.Hint"] = "Copy backend diagnostics",
        ["Shell.Backend.Action.StartDaemon.Label"] = "Start local daemon",
        ["Shell.Backend.Action.StartDaemon.Hint"] = "Try starting the local daemon again"
    };

    public static string Get(string resourceKey)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(resourceKey);

        return Strings.TryGetValue(resourceKey, out var value)
            ? value
            : throw new KeyNotFoundException($"No desktop string resource exists for key '{resourceKey}'.");
    }
}
