<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Sockseek.Core</AssemblyName>
    <RootNamespace>Sockseek.Core</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.YouTube.v3" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="SmallestCSVParser" />
    <PackageReference Include="Soulseek" />
    <PackageReference Include="SpotifyAPI.Web" />
    <PackageReference Include="SpotifyAPI.Web.Auth" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="YoutubeExplode" />
  </ItemGroup>

</Project>
