<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Sockseek.Integrations.Abstractions</AssemblyName>
    <RootNamespace>Sockseek.Integrations.Abstractions</RootNamespace>
  </PropertyGroup>
</Project>
